name: ResourcePack
version: ${project.version}
main: net.minevn.resourcepack.ResourcePack
api-version: 1.12
authors: [ Claus ]
commands:
  loadrsp:
    permission: resourcepack.load
  setrsploc:
    permission: resourcepack.setrsploc
